name: example
description: A new Flutter project.
version: 1.0.1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  provider: any
  # For Dio Kit
  dio: any

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  flutter_ume:
    path: ../

flutter:
  uses-material-design: true
